<a href="https://colab.research.google.com/github/Tina-223/DBscan/blob/main/test2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec

df = pd.read_csv('all_drinks.csv')

df = df.drop(['strCategory','dateModified','strDrinkThumb', 'strGlass', 'strIBA', 'strInstructions', 'strMeasure1', 'strMeasure2', 'strMeasure3', 'strMeasure4', 'strMeasure5', 'strMeasure6', 'strMeasure7', 'strMeasure8',
                          'strMeasure9', 'strMeasure10', 'strMeasure11', 'strMeasure12', 'strMeasure13', 'strMeasure14', 'strMeasure15', 'strVideo', 'strIngredient13', 'strIngredient14', 'strIngredient15'], axis=1)
df.head()

,Unnamed: 0,strDrink,idDrink,strAlcoholic,strIngredient1,strIngredient10,strIngredient11,strIngredient12,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9
0,0,'57 Chevy with a White License Plate,14029,Alcoholic,Creme de Cacao,NaN,NaN,NaN,Vodka,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1-900-FUK-MEUP,15395,Alcoholic,Absolut Kurant,NaN,NaN,NaN,Grand Marnier,Chambord raspberry liqueur,Midori melon liqueur,Malibu rum,Amaretto,Cranberry juice,Pineapple juice,NaN
2,2,110 in the shade,15423,Alcoholic,Lager,NaN,NaN,NaN,Tequila,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,151 Florida Bushwacker,14588,Alcoholic,Malibu rum,NaN,NaN,NaN,Light rum,151 proof rum,Dark Creme de Cacao,Cointreau,Milk,Coconut liqueur,Vanilla ice-cream,NaN
4,4,155 Belmont,15346,Alcoholic,Dark rum,NaN,NaN,NaN,Light rum,Vodka,Orange juice,NaN,NaN,NaN,NaN,NaN

In [30]:
alcoholic = {'Alcoholic' : 2, 'Optional alcohol': 1, 'Non alcoholic': 0}
df['strAlcoholic'] = df['strAlcoholic'].map(alcoholic)

df3 = pd.DataFrame(columns = ['final'])

final = []
for row in range(df.shape[0]):
  ingredients = []
  for i in range(1, 13):
    column = 'strIngredient'+ str(i)
    ingr = df.loc[row][column]
    if str(ingr) == '' or str(ingr) == 'nan':
      continue
    elif ingr not in ingredients :
      ingredient = str(ingr).lower()
      ingredients.append(ingredient)
  final.append(ingredients)
  
model = Word2Vec(sentences=final, size=100, window=5, min_count=5, workers=4, sg=0)

WARNING:gensim.models.base_any2vec:under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha decay
<ipython-input-30-2cbbfdea0362>:23: DeprecationWarning: Call to deprecated `similarity` (Method will be removed in 4.0.0, use self.wv.similarity() instead).
  res = model.similarity(final[row])

TypeError: ignored

In [52]:
model_result = model.wv.most_similar('orange')
print(len(model_result))
print(model_result)

10
[('red wine', 0.2742813527584076), ('kahlua', 0.21077948808670044), ('scotch', 0.20932134985923767), ('cloves', 0.20094889402389526), ('cranberry juice', 0.1917610615491867), ('sour mix', 0.18364670872688293), ('7-up', 0.1789179891347885), ('triple sec', 0.17841836810112), ('apple juice', 0.17569676041603088), ('rum', 0.16856423020362854)]

In [56]:
from sklearn.cluster import DBSCAN

dff = pd.DataFrame(model_result)
df_train = dff.drop(dff.columns[[0]], axis=1)

clustering = DBSCAN(eps= 0.005, min_samples=3).fit(df_train)
df_train.loc[:,'Cluster'] = clustering.labels_
df_train.Cluster.value_counts().to_frame()

    Cluster
-1        6
 0        4